### PR TITLE
Add keyboard controls

### PR DESCRIPTION
**Pull request by Glutanimate**
The commits in this pull request add two hotkeys to the add-on:

- <kbd>F9</kbd> to toggle between frozen and unfrozen on the current field
- <kbd>SHIFT</kbd> + <kbd>F9</kbd> to unfreeze all fields

### CODE REVIEW

**Comment by tmbb** [comment]
Would you mind if I stole your Addon Description for my new docs?

**Comment by Glutanimate** [comment]
No, not at all. Please feel free to use it! Though you'll probably want to trim it down a bit and remove the sections that aren't relevant any more.

On another note, have you decided yet if you're going to re-upload your add-ons to AnkiWeb?

**Comment by tmbb** [comment]
Probably tonight (GMT+0). I've already created a new account and I'm in the process of rewriting the addon descriptions (they were deleted together with my old account).

I'm also writing the docs for some as of yet unpublished addons which I may publish tonight too.

**Comment by tmbb** [comment]
And by the way, thanks for having uploaded my addons while I decided whether to create a new account or not.

**Comment by Glutanimate** [comment]
You're welcome! Such a shame that your account was removed just like that, but I'm glad you're back. 

The add-on system really needs an overhaul. Over the past couple of weeks the re-upload of I/O got about 600 downloads alone. Can't imagine how many the original upload had. To see as important an add-on as this get taken down simply because you weren't active for a few months really makes you wonder what the Anki dev-team was thinking when establishing this policy.

**Comment by tmbb** [comment]
Last time I checked there were about 9,000 downloads. Just before it was brought down there must have been 15,000 or something. It is very popular among med students. I don't blame Anki's dev team, and their position makes sense (addons usually need some maintenance when a major anki version comes out). The problem is that the internet is full of links to the old addon page, which is not coming back. But people seem to have found your new page very quickly, so I'm not too worried.

**Comment by Glutanimate** [comment]
That's quite an impressive number.

I actually hadn't thought of the maintenance aspect of it, but it's reasonable now that you say it. Though placing a warning on the add-on page if it hasn't been actively maintained, would seem seem like a less harsh option to me; and it would allow people to still download and try the add-on for themselves if they wished. There seem to be quite a few add-ons on AnkiWeb that don't link to any repository and/or author information. Deleting these would pretty much erase them from existence, unless someone decided to re-upload their local copy

**Comment by tmbb** [comment]
Would you mind changing the license to BSD? It's the same to me, really, but it's simpler if all my addons are under the same license

**Comment by Glutanimate** [comment]
Done.

Oh, BTW: I almost forgot about this, but I've made a few changes to my local copy of Image Occlusion (keyboard shortcuts, etc.). They're not committed to any repo, yet, but I could prepare them and file a few pull requests if that's fine with you. The only issue I see is that the branch on bitbucket which I've used for my changes is ahead by couple or so commits to the one on GitHub. If you were to sync these two it would make this easier and prevent some possible issues.

**Pull request merged**
